---
title: "AVG Seasonal Temperature Model"
author: "Roberto Saravia"
date: "2/8/2022"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(
  echo = TRUE,
  warning = FALSE
)
library(tidyverse)
```

Read cherry blossom data.
```{r}
cherry <- read.csv("data/washingtondc.csv") %>% 
  bind_rows(read.csv("data/liestal.csv")) %>% 
  bind_rows(read.csv("data/kyoto.csv"))
```


Collect temperature data.
```{r}
library(rnoaa)
stations <- ghcnd_stations()

#' Get the annual average maximum temperature at the given station,
#' separated into the 4 meteorological seasons (Winter, Spring, Summer, Fall).
#' 
#' The seasons are span 3 months each.
#' Winter is from December to February, Spring from March to May,
#' Summer from June to August, and Fall from September to November.
#' Note that December is counted towards the Winter of the next year, i.e.,
#' temperatures in December 2020 are accounted for in Winter 2021.
#' 
#' @param stationid the `rnoaa` station id (see [ghcnd_stations()])
#' @param varid the `gchnd_stations()` vars (single)
#' @return a data frame with columns
#'   - `year` ... the year of the observations
#'   - `season` ... the season (Winter, Spring, Summer, Fall)
#'   - `tmax_avg` ... average maximum temperature in tenth degree Celsius
#'   - `tmin_avg` ... average minimum temperature in tenth degree Celcius
get_temperature <- function (stationid) {
  ghcnd_search(stationid = stationid, var = c("tmin"), 
               refresh = T)[[1]] %>%
  mutate(year = as.integer(format(date, "%Y")),
         month = as.integer(strftime(date, '%m')) %% 12, # make December "0"
         season = cut(month, breaks = c(0, 2, 5, 8, 11),
                      include.lowest = TRUE,
                      labels = c("Winter", "Spring", "Summer", "Fall")),
         year = if_else(month == 0, year + 1L, year)) %>%
  group_by(year, season) %>%
  summarize(tmin_avg = mean(tmin, na.rm = TRUE))
}


historic_temperatures_tmax <-
  tibble(location = "washingtondc", get_temperature("USC00186350")) %>%
  bind_rows(tibble(location = "liestal", get_temperature("GME00127786"))) %>%
  bind_rows(tibble(location = "kyoto", get_temperature("JA000047759"))) %>%
  bind_rows(tibble(location = "vancouver", get_temperature("CA001108395")))

# get_temperature() replace tmax in var = c("tmax")
# to tmin
historic_temperatures_tmin <-
  tibble(location = "washingtondc", get_temperature("USC00186350")) %>%
  bind_rows(tibble(location = "liestal", get_temperature("GME00127786"))) %>%
  bind_rows(tibble(location = "kyoto", get_temperature("JA000047759"))) %>%
  bind_rows(tibble(location = "vancouver", get_temperature("CA001108395")))

# get_temperature() replace tmax in var = c("tmax")
# to tavg
historic_temperatures_tavg <-
  tibble(location = "washingtondc", get_temperature("USC00186350"))


# get_temperature() replace tmax in var = c("tmax")
# to tavg
historic_prcp <-
  tibble(location = "washingtondc", get_temperature("USC00186350")) %>%
  bind_rows(tibble(location = "liestal", get_temperature("GME00127786"))) %>%
  bind_rows(tibble(location = "kyoto", get_temperature("JA000047759"))) %>%
  bind_rows(tibble(location = "vancouver", get_temperature("CA001108395")))
```

Join datasets.
```{r}
yearly_temp <- cherry %>%
  filter(location == "washingtondc")

historic_temperatures_tmax <- historic_temperatures_tmax %>%
  filter(location == "washingtondc")

historic_temperatures_tmin <- historic_temperatures_tmin %>%
  filter(location == "washingtondc")

datasets <- list(historic_temperatures_tmax, 
                 historic_temperatures_tmin, 
                 yearly_temp)

yearly_temps_dc <- full_join(historic_temperatures_tmax,
          historic_temperatures_tmin) %>%
  left_join(yearly_temp)
```

Correlations.
```{r}
model_data %>%
filter(season == "Summer") %>%
ggplot(aes(x = tmin_avg, y = bloom_doy)) +
  geom_point()

spring_temps_dc <- yearly_temps_dc %>%
filter(season == "Spring")

# We have to consider the previous summer for the current year.
# For example a peak bloom on 2019, we would consider the 
# tmax_avg for the summer of 2018
summer_temps_dc <- yearly_temps_dc %>%
  filter(season == "Summer")

tmp1 <- summer_temps_dc$tmax_avg
tmp1 <- tmp1[-length(tmp1)]
tmp2 <- summer_temps_dc$tmin_avg
tmp2 <- tmp2[-length(tmp2)]
summer_temps_dc <- summer_temps_dc[-c(1), ]
summer_temps_dc$tmax_avg <- tmp1
summer_temps_dc$tmin_avg <- tmp2

# Spring data was not recorded for the year 1953
# Drop that value in summer too.
summer_temps_dc <- summer_temps_dc[-c(3), ]
# Drop Spring for 1950 since we could not include that year
# in the summer.
spring_temps_dc <- spring_temps_dc[-c(1), ]

# Finalize the data that will be used to create our base
# model.
model_data <- full_join(summer_temps_dc,
          spring_temps_dc)

# Tmax_avg and Tmin_avg interaction, has the same significance 
# as difference ((tmax_avg - tmin_avg) / 2)
model_data <- model_data %>%
  mutate(difference = (tmax_avg - tmin_avg) /2)
```

Create the basic linear regression model for Washington DC.
```{r}
model1 <- lm(data = model_data, 
             formula = bloom_doy ~ difference*year + tmax_avg*season * season*year)
```

Get more data.
```{r}
get_all_variables <- function (stationid) {
  ghcnd_search(stationid = stationid, refresh = T)
}

all_data <- get_all_variables("USC00186350")
historic_weather <-
  tibble(location = "washingtondc", get_all_variables("USC00186350")) %>%
  bind_rows(tibble(location = "liestal", get_all_variables("GME00127786"))) %>%
  bind_rows(tibble(location = "kyoto", get_all_variables("JA000047759"))) %>%
  bind_rows(tibble(location = "vancouver", get_all_variables("CA001108395")))

t2 <- all_data %>%
  reduce(full_join, by = c("date", "id", "qflag", "mflag",
                           "sflag"))
t2 <- t2 %>%
   mutate(year = as.integer(format(date, "%Y")),
         month = as.integer(strftime(date, '%m')) %% 12, # make December "0"
         season = cut(month, breaks = c(0, 2, 5, 8, 11),
                      include.lowest = TRUE,
                      labels = c("Winter", "Spring", "Summer", "Fall")),
         year = if_else(month == 0, year + 1L, year),
         difference = (tmax - tmin)/2)

t2 <- t2 %>%
  dplyr::select(year, season, date, difference, tmax, tmin, prcp, snow, snwd, tobs)


t2[is.na(t2)] <- 0

model2 <- lm(data = t2, 
             formula = difference ~ date + prcp + snwd + season)
```

```{r}
library(rnoaa)
dc <- ghcnd_stations(id = "USC00186350")
dc_sub <- subset(dc, id == "USC00186350")

dc_sub

dc %>%
  filter(id == "USC00186350")


dc_meteo_month <- ghcnd(stationid = "USC00186350", refresh = T)


dc_meteo_day <- ghcnd_search(stationid = "USC00186350", refresh = T)

dc_meteo_day[["tmax"]] %>%
  left_join(dc_meteo_day[["tmin"]]) %>%
  left_join(dc_meteo_day[["prcp"]]) %>%
  left_join(dc_meteo_day[["snow"]]) %>%
  left_join(dc_meteo_day[["snwd"]]) %>%
  left_join(dc_meteo_day[["tobs"]]) %>%
  left_join(dc_meteo_day[["dapr"]]) %>%
  left_join(dc_meteo_day[["mdpr"]]) %>%
  left_join(dc_meteo_day[["wt04"]]) %>%
  left_join(dc_meteo_day[["wt05"]]) %>%
  left_join(dc_meteo_day[["wt01"]]) %>%
  left_join(dc_meteo_day[["wt03"]]) %>%
  left_join(dc_meteo_day[["wt11"]]) %>%  
  left_join(dc_meteo_day[["dasf"]]) %>%             
  left_join(dc_meteo_day[["mdsf"]]) %>%  
  left_join(dc_meteo_day[["wesd"]])


dc_meteo_all <- dc_meteo_day %>%
  reduce(full_join, by = c("date", "id", "qflag", "sflag", "mflag"))

dc_meteo_all_subset <- dc_meteo_all[c(-4,-5,-6)]



dc_something <- dc_meteo_all_subset %>%
  mutate(year = lubridate::year(dc_meteo_all_subset$date))

dc_something <- 
  dc_something %>%
  mutate(year = as.integer(format(date, "%Y")),
         month = as.integer(strftime(date, '%m')) %% 12, # make December "0"
         season = cut(month, breaks = c(0, 2, 5, 8, 11),
                      include.lowest = TRUE,
                      labels = c("Winter", "Spring", "Summer", "Fall")),
         year = if_else(month == 0, year + 1L, year)) %>%
  group_by(year, season) %>%
  summarize(tmin = mean(tmin, na.rm = T),
            tmax = mean(tmax, na.rm = T),
            prcp = mean(prcp, na.rm = T),
            snow = mean(snow, na.rm = T),
            snwd = mean(snwd, na.rm = T),
            tobs = mean(tobs, na.rm = T),
            dapr = mean(dapr, na.rm = T),
            mdpr = mean(mdpr, na.rm = T),
            wt04 = mean(wt04, na.rm = T),
            wt05 = mean(wt05, na.rm = T),
            wt01 = mean(wt01, na.rm = T),
            wt03 = mean(wt03, na.rm = T),
            wt11 = mean(wt11, na.rm = T),
            dasf = mean(dasf, na.rm = T),
            mdsf = mean(mdsf, na.rm = T),
            wt06 = mean(wt06, na.rm = T),
            wesd = mean(wesd, na.rm = T))

dc_something$dapr[is.nan(dc_something$dapr)]<-0
dc_something$mdpr[is.nan(dc_something$mdpr)]<-0
dc_something$wt04[is.nan(dc_something$wt04)]<-0
dc_something$wt05[is.nan(dc_something$wt05)]<-0
dc_something$wt01[is.nan(dc_something$wt01)]<-0
dc_something$wt03[is.nan(dc_something$wt03)]<-0
dc_something$wt11[is.nan(dc_something$wt11)]<-0
dc_something$dasf[is.nan(dc_something$dasf)]<-0
dc_something$mdsf[is.nan(dc_something$mdsf)]<-0
dc_something$wesd[is.nan(dc_something$wesd)]<-0
dc_something$wesdf <- NULL
dc_something$wt06[is.nan(dc_something$wt06)]<-0

dc_seasonal_weather <- dc_something %>%
  pivot_wider(names_from = season, values_from = c(
    tmin, tmax, prcp, snow, snwd, tobs, dapr,
    mdpr, wt04, wt05, wt01, wt03, wt11, dasf,
    mdsf, wt06, wesd
  )) %>%
  na.omit()

dc_seasonal_weather <- cherry %>%
  dplyr::select(year, bloom_doy) %>%
  right_join(dc_seasonal_weather, by = "year")

# -----------------------OLD-----------------------
# dc_tmin <- dc_something %>%
#   group_by(year) %>%
#   summarise(min = mean(tmin, na.rm = T))
# dc_tmax <- dc_something %>%
#   group_by(year) %>%
#   summarise(max = mean(tmax, na.rm = T))
# dc_prcp <- dc_something %>%
#   group_by(year) %>%
#   summarise(prcp = mean(prcp, na.rm = T))
# dc_snow <- dc_something %>%
#   group_by(year) %>%
#   summarise(snow = mean(snow, na.rm = T))
# dc_snwd <- dc_something %>%
#   group_by(year) %>%
#   summarise(snwd = mean(snwd, na.rm = T))
# dc_tobs <- dc_something %>%
#   group_by(year) %>%
#   summarise(tobs = mean(tobs, na.rm = T))
# dc_dapr <- dc_something %>%
#   group_by(year) %>%
#   summarise(dapr = mean(dapr, na.rm = T))
# dc_mdpr <- dc_something %>%
#   group_by(year) %>%
#   summarise(mdpr = mean(mdpr, na.rm = T))
# dc_wt04 <- dc_something %>%
#   group_by(year) %>%
#   summarise(wt04 = mean(wt04, na.rm = T))
# dc_wt05 <- dc_something %>%
#   group_by(year) %>%
#   summarise(wt05 = mean(wt05, na.rm = T))
# dc_wt01 <- dc_something %>%
#   group_by(year) %>%
#   summarise(wt01 = mean(wt01, na.rm = T))
# dc_wt03 <- dc_something %>%
#   group_by(year) %>%
#   summarise(wt03 = mean(wt03, na.rm = T))
# dc_wt11 <- dc_something %>%
#   group_by(year) %>%
#   summarise(wt11 = mean(wt11, na.rm = T))
# dc_dasf <- dc_something %>%
#   group_by(year) %>%
#   summarise(dasf = mean(dasf, na.rm = T))
# dc_mdsf <- dc_something %>%
#   group_by(year) %>%
#   summarise(mdsf = mean(mdsf, na.rm = T))
# dc_wt06 <- dc_something %>%
#   group_by(year) %>%
#   summarise(wt06 = mean(wt06, na.rm = T))
# dc_wesd <- dc_something %>%
#   group_by(year) %>%
#   summarise(wesd = mean(wesd, na.rm = T))
# 
# dc_big <- dc_tmin %>%
#   left_join(dc_prcp) %>%
#   left_join(dc_tmax) %>%
#   left_join(dc_snow) %>%
#   left_join(dc_snwd) %>%
#   left_join(dc_tobs) %>%
#   left_join(dc_dapr) %>%
#   left_join(dc_mdpr) %>%
#   left_join(dc_wt04) %>%
#   left_join(dc_wt05) %>%
#   left_join(dc_wt01) %>%
#   left_join(dc_wt03) %>%
#   left_join(dc_wt11) %>%
#   left_join(dc_dasf) %>%
#   left_join(dc_mdsf) %>%
#   left_join(dc_wt06) %>%
#   left_join(dc_wesd)
# 
# dc_big$dapr[is.nan(dc_big$dapr)]<-0
# dc_big$mdpr[is.nan(dc_big$mdpr)]<-0
# dc_big$wt04[is.nan(dc_big$wt04)]<-0
# dc_big$wt05[is.nan(dc_big$wt05)]<-0
# dc_big$wt01[is.nan(dc_big$wt01)]<-0
# dc_big$wt03[is.nan(dc_big$wt03)]<-0
# dc_big$wt11[is.nan(dc_big$wt11)]<-0
# dc_big$dasf[is.nan(dc_big$dasf)]<-0
# dc_big$mdsf[is.nan(dc_big$mdsf)]<-0
# dc_big$wesd[is.nan(dc_big$wesd)]<-0
# dc_big$wesdf <- NULL
# dc_big$wt06[is.nan(dc_big$wt06)]<-0
# 
# 
# dc_solar_irradiation <- read.csv("./data/DC-Solar-Irradiance/1144937_38.89_-77.02_1999.csv", skip = 2)

# for(year in 1999:2020) {
#   path <- paste0("./data/DC-Solar-Irradiance/1144937_38.89_-77.02_",
#                year, ".csv")
#   dc_solar_irradiation <-
#   bind_rows(dc_solar_irradiation,
#   read.csv(path, skip = 2))
# }
# 
# 
# dc_dew_point <- read.csv("./data/csv.noaa.dew/1.csv")
# for(num in 2:8) {
#   path <- paste0("./data/csv.noaa.dew/",
#                num, ".csv")
#   print(path)
#   dc_dew_point <-
#   bind_rows(dc_dew_point,
#   read.csv(path))
#   dc_dew_point <- na.exclude(dc_dew_point)
# }
# library(data.table)
# library(dplyr)
# library(purrr)
# library(lubridate)
# files <- c("./data/csv.noaa.dew/1.csv",
#            "./data/csv.noaa.dew/2.csv",
#            "./data/csv.noaa.dew/3.csv",
#            "./data/csv.noaa.dew/4.csv",
#            "./data/csv.noaa.dew/5.csv",
#            "./data/csv.noaa.dew/6.csv",
#            "./data/csv.noaa.dew/7.csv",
#            "./data/csv.noaa.dew/8.csv")
# 
# # Identify columns you need
# myColumns = c("DATE", "DailyAverageDewPointTemperature")
# 
# 
# fread_allfiles <- function(file, columns){
#   x <- fread(file, select = columns) %>% 
#     dplyr::select(everything())   # 
#   return(x)
# }
# 
# df_all <- files %>% 
#   map_df(~ fread_allfiles(.,myColumns))
# df_all <- na.exclude(df_all)
# 
# df_all <- df_all %>%
#   mutate(year = lubridate::year(df_all$DATE),
#          month = lubridate::month(df_all$DATE))
# # 2011 - 2012, 1993 - 1992, 1972 - 1973, 1962-1963, 1953 - 1952
# df_all <- df_all %>%
#    filter(month < 4 & month >= 1) %>%
#    group_by(year) %>%
#    summarise(avg_dew = mean(avg_dew))
# 
# # df_all <- rename(df_all, avg_dew = DailyAverageDewPointTemperature)
# df <- list.files(path="./data/csv.noaa.dew/", full.names = T) %>%
#   lapply(read_csv, col_types = "character") %>% 
#   bind_rows

# dc_solar_irradiation <- dc_solar_irradiation[1:(length(dc_solar_irradiation)-1)]
# dc_solar_mean <- dc_solar_irradiation %>%
#    filter(Month < 4) %>%
#    group_by(Year) %>%
#    summarise(avg_ghi = mean(GHI),
#              avg_dni = mean(DNI),
#              avg_dhi = mean(DHI),
#              avg_clearsky = mean(Clearsky.GHI),
#              avg_dew = mean(Dew.Point),
#              avg_albedo = mean(Surface.Albedo),
#              avg_windspeed = mean(Wind.Speed),
#              avg_humidity = mean(Relative.Humidity),
#              avg_temp = mean(Temperature),
#              avg_pressure = mean(Pressure)
# )
# dc_solar_mean <- rename(dc_solar_mean, year = Year)
# dc_big_bloom_day <- cherry %>%
#   select(year, bloom_doy) %>%
#   left_join(dc_big, by = "year")
# 
# dc_big_bloom_dey <- dc_big %>%
#   left_join(cherry, by = "year")
```

Lasso Regression and Stepwise
```{r}
library(glmnet)
library(MASS)
library(leaps)
library(caret)


# ---------------LASSO-----------------------------------
y <- data.matrix(dc_seasonal_weather$bloom_doy)

#define matrix of predictor variables
x <- data.matrix(dc_seasonal_weather[, -2])


#perform k-fold cross-validation to find optimal lambda value
cv_model <- cv.glmnet(x, y, alpha = 1)

#find optimal lambda value that minimizes test MSE
best_lambda <- cv_model$lambda.min
best_lambda

best_model <- glmnet(x, y, alpha = 1, lambda = best_lambda)
coef(best_model)


dc_big_bloom_dey$location <- NULL
dc_big_bloom_dey$bloom_date <- NULL
big_model_dc <- lm(bloom_doy ~ tmax_Winter + tmax_Spring + 
                     snow_Spring + tobs_Summer + tobs_Fall + 
                     dapr_Spring + mdpr_Spring + wt04_Spring + 
                     wt01_Winter + wt01_Spring + wt03_Fall + 
                     wt03_Spring
                     ,data= dc_seasonal_weather)

train.control <- trainControl(method = "cv", number = 10)
step.model <- train(bloom_doy ~ . -year, data = dc_seasonal_weather,
                    method = "lmStepAIC", 
                    trControl = train.control,
                    trace = FALSE
)
# Model accuracy
step.model$results
# Final model coefficients
step.model$finalModel
# Summary of the model
summary(step.model$finalModel)
# Train the model
```

RandomForest for fun :)
```{r}
library(randomForest)
library(ROCR)
sample <- sample(1:nrow(dc_seasonal_weather), 0.7 * nrow(dc_seasonal_weather))
train.x <- dc_seasonal_weather[sample, -2]
train.y <- dc_seasonal_weather[sample, 2]
test.x <- dc_seasonal_weather[-sample, -2]
test.y <- dc_seasonal_weather[-sample, 2]

rf <- randomForest::randomForest(train.x, train.y,
                                 test.x, test.y,
                                 importance = T, proximity = T,
                                 ntree = 500,
                                 mtry = 7)

# extract OOB & validation errors
oob <- sqrt(rf$mse)
validation <- sqrt(rf$test$mse)

# compare error rates
tibble::tibble(
  `Out of Bag Error` = oob,
  `Test error` = validation,
  ntrees = 1:rf$ntree
) %>% 
  gather(Metric, RMSE, -ntrees) %>%
  ggplot(aes(ntrees, RMSE, color = Metric)) +
  geom_line() +
  xlab("Number of trees")

m2 <- tuneRF(
  x          = train.x,
  y          = train.y,
  ntreeTry   = 500,
  mtryStart  = 10,
  stepFactor = 1.5,
  improve    = 0.01,
  trace      = FALSE      # to not show real-time progress 
)

# hyperparameter grid search
hyper_grid <- expand.grid(
  mtry       = seq(1, 18, by = 1),
  node_size  = seq(1, 9, by = 2),
  sampe_size = c(.55, .632, .70, .80),
  OOB_RMSE   = 0
)

library(ranger)
library(broom)
train <- dc_seasonal_weather[sample, ]
for(i in 1:nrow(hyper_grid)) {
  
  # train model
  model <- ranger(
    formula         = bloom_doy ~ ., 
    data            = train, 
    num.trees       = 500,
    mtry            = hyper_grid$mtry[i],
    min.node.size   = hyper_grid$node_size[i],
    sample.fraction = hyper_grid$sampe_size[i],
    seed            = 123,
    importance = 'impurity'
  )
  
  # add OOB error to grid
  hyper_grid$OOB_RMSE[i] <- sqrt(model$prediction.error)
}

hyper_grid %>% 
  dplyr::arrange(OOB_RMSE) %>%
  head(10)

model$variable.importance %>% 
  tidy() %>%
  dplyr::arrange(desc(x)) %>%
  dplyr::top_n(10) %>%
  ggplot(aes(reorder(names, x), x)) +
  geom_col() +
  coord_flip() +
  ggtitle("Top 10 important variables")


```

Jon's code ramblings
```{r}


trees_lm <- lm(bloom_doy ~ tmin_Spring+tobs_Summer+year+tobs_Fall+tmax_Spring+tobs_Spring+prcp_Fall+snow_Spring+tmax_Winter+tmax_Fall,data = dc_seasonal_weather)

lasso_lm <- lm(bloom_doy ~ wt11_Fall+wt03_Winter+wt03_Summer+wt01_Spring+wt01_Fall+wt04_Spring+mdpr_Fall+dapr_Spring+dapr_Winter+dapr_Fall+tobs_Spring+snwd_Winter+snow_Spring+snow_Winter+prcp_Spring+prcp_Winter+prcp_Fall+prcp_Summer+tmax_Spring+tmin_Fall+tmin_Summer,data = dc_seasonal_weather)

cutdown_lasso_lm <- lm(bloom_doy ~ wt03_Winter+wt03_Summer+mdpr_Fall+dapr_Spring+dapr_Fall+tobs_Spring+prcp_Fall+tmax_Spring+tmin_Fall+tmin_Summer,data = dc_seasonal_weather)

summary(trees_lm)

summary(lasso_lm)

summary(cutdown_lasso_lm)


cherry_pre1948 <- subset(cherry, year >= 1948)

just_year <- lm(bloom_doy ~ year+lat+long, data = subset(cherry_pre1948, location == "washingtondc"))

summary(just_year)

swiss <- lm(bloom_doy ~ year, data = subset(cherry_pre1948, location == "liestal"))
japan <- lm(bloom_doy ~ year, data = subset(cherry_pre1948, location == "kyoto"))
usa <- lm(bloom_doy ~ year, data = subset(cherry_pre1948, location == "washingtondc"))

summary(usa)
summary(swiss)
summary(japan)


ggplot(data = cherry_pre1948, aes(year,bloom_doy, color = location)) + geom_point() + geom_smooth(method = "lm")


dc_seasonal_weather_1980s <- subset(dc_seasonal_weather, year >= 1980)

ggplot(data = dc_seasonal_90s, aes(year,wt03_Winter)) + geom_point() + geom_smooth(method = "lm")
ggplot(data = dc_seasonal_90s, aes(year,wt03_Summer)) + geom_point() + geom_smooth(method = "lm")
ggplot(data = dc_seasonal_90s, aes(year,mdpr_Fall)) + geom_point() + geom_smooth(method = "lm")
ggplot(data = dc_seasonal_90s, aes(year,dapr_Spring)) + geom_point() + geom_smooth(method = "lm")
ggplot(data = dc_seasonal_90s, aes(year,dapr_Fall)) + geom_point() + geom_smooth(method = "lm")
ggplot(data = dc_seasonal_weather, aes(year,tobs_Spring)) + geom_point() + geom_smooth(method = "lm")
ggplot(data = dc_seasonal_90s, aes(year,prcp_Fall)) + geom_point() + geom_smooth(method = "lm")
ggplot(data = dc_seasonal_90s, aes(year,tmax_Spring)) + geom_point() + geom_smooth(method = "lm")
ggplot(data = dc_seasonal_90s, aes(year,tmin_Fall)) + geom_point() + geom_smooth(method = "lm")
ggplot(data = dc_seasonal_90s, aes(year,tmin_Summer)) + geom_point() + geom_smooth(method = "lm")

trees_lm <- lm(bloom_doy ~ tmin_Spring+tobs_Summer+year+tobs_Fall+tmax_Spring+tobs_Spring+prcp_Fall+snow_Spring+tmax_Winter+tmax_Fall,data = dc_seasonal_weather_1980s)

summary(trees_lm)

lasso_lm <- lm(bloom_doy ~ wt11_Fall+wt03_Winter+wt03_Summer+wt01_Spring+wt01_Fall+wt04_Spring+mdpr_Fall+dapr_Spring+dapr_Winter+dapr_Fall+tobs_Spring+snwd_Winter+snow_Spring+snow_Winter+prcp_Spring+prcp_Winter+prcp_Fall+prcp_Summer+tmax_Spring+tmin_Fall+tmin_Summer,data = dc_seasonal_weather_1980s)

cutdown_lasso_lm <- lm(bloom_doy ~ wt03_Winter+wt03_Summer+mdpr_Fall+dapr_Spring+dapr_Fall+tobs_Spring+prcp_Fall+tmax_Spring+tmin_Fall+tmin_Summer,data = dc_seasonal_weather_1980s)

summary(lasso_lm)

summary(cutdown_lasso_lm)

```

New Genny
```{r}
dc <- ghcnd_stations(id = "USC00186350")
dc_sub <- subset(dc, id == "USC00186350")

dc_sub

dc %>%
  filter(id == "USC00186350")


dc_meteo_month <- ghcnd(stationid = "USC00186350", refresh = T)


dc_meteo_day <- ghcnd_search(stationid = "USC00186350", refresh = T)

dc_meteo_day[["tmax"]] %>%
  left_join(dc_meteo_day[["tmin"]]) %>%
  left_join(dc_meteo_day[["prcp"]]) %>%
  left_join(dc_meteo_day[["snow"]]) %>%
  left_join(dc_meteo_day[["snwd"]]) %>%
  left_join(dc_meteo_day[["tobs"]]) %>%
  left_join(dc_meteo_day[["dapr"]]) %>%
  left_join(dc_meteo_day[["mdpr"]]) %>%
  left_join(dc_meteo_day[["wt04"]]) %>%
  left_join(dc_meteo_day[["wt05"]]) %>%
  left_join(dc_meteo_day[["wt01"]]) %>%
  left_join(dc_meteo_day[["wt03"]]) %>%
  left_join(dc_meteo_day[["wt11"]]) %>%  
  left_join(dc_meteo_day[["dasf"]]) %>%             
  left_join(dc_meteo_day[["mdsf"]]) %>%  
  left_join(dc_meteo_day[["wesd"]])


dc_meteo_all <- dc_meteo_day %>%
  reduce(full_join, by = c("date", "id", "qflag", "sflag", "mflag"))

dc_meteo_all_subset <- dc_meteo_all[c(-4,-5,-6)]



dc_something <- dc_meteo_all_subset %>%
  mutate(year = lubridate::year(dc_meteo_all_subset$date))

dc_something <- 
  dc_something %>%
  mutate(year = as.integer(format(date, "%Y")),
         month = as.integer(strftime(date, '%m')) %% 12, # make December "0"
         season = cut(month, breaks = c(0, 2, 5, 8, 11),
                      include.lowest = TRUE,
                      labels = c("Winter", "Spring", "Summer", "Fall")),
         year = if_else(month == 0, year + 1L, year)) %>%
  group_by(year, season) %>%
  summarize(tmin = mean(tmin, na.rm = T),
            tmax = mean(tmax, na.rm = T),
            prcp = mean(prcp, na.rm = T),
            snow = mean(snow, na.rm = T),
            snwd = mean(snwd, na.rm = T),
            tobs = mean(tobs, na.rm = T),
            dapr = mean(dapr, na.rm = T),
            mdpr = mean(mdpr, na.rm = T),
            wt04 = mean(wt04, na.rm = T),
            wt05 = mean(wt05, na.rm = T),
            wt01 = mean(wt01, na.rm = T),
            wt03 = mean(wt03, na.rm = T),
            wt11 = mean(wt11, na.rm = T),
            dasf = mean(dasf, na.rm = T),
            mdsf = mean(mdsf, na.rm = T),
            wt06 = mean(wt06, na.rm = T),
            wesd = mean(wesd, na.rm = T))

dc_something$dapr[is.nan(dc_something$dapr)]<-0
dc_something$mdpr[is.nan(dc_something$mdpr)]<-0
dc_something$wt04[is.nan(dc_something$wt04)]<-0
dc_something$wt05[is.nan(dc_something$wt05)]<-0
dc_something$wt01[is.nan(dc_something$wt01)]<-0
dc_something$wt03[is.nan(dc_something$wt03)]<-0
dc_something$wt11[is.nan(dc_something$wt11)]<-0
dc_something$dasf[is.nan(dc_something$dasf)]<-0
dc_something$mdsf[is.nan(dc_something$mdsf)]<-0
dc_something$wesd[is.nan(dc_something$wesd)]<-0
dc_something$wesdf <- NULL
dc_something$wt06[is.nan(dc_something$wt06)]<-0

dc_seasonal_weather <- dc_something %>%
  pivot_wider(names_from = season, values_from = c(
    tmin, tmax, prcp, snow, snwd, tobs, dapr,
    mdpr, wt04, wt05, wt01, wt03, wt11, dasf,
    mdsf, wt06, wesd
  )) %>%
  na.omit()

dc_seasonal_weather <- cherry %>%
  dplyr::select(year, bloom_doy) %>%
  right_join(dc_seasonal_weather, by = "year")


dc_solar_irradiation <- read.csv("./data/DC-Solar-Irradiance/1144937_38.89_-77.02_1999.csv", skip = 2)

for(year in 1999:2020) {
  path <- paste0("./data/DC-Solar-Irradiance/1144937_38.89_-77.02_",
               year, ".csv")
  dc_solar_irradiation <-
  bind_rows(dc_solar_irradiation,
  read.csv(path, skip = 2))
}



 library(data.table)
 library(dplyr)
 library(purrr)
 library(lubridate)
 

 dc_solar_irradiation <- dc_solar_irradiation[1:(length(dc_solar_irradiation)-1)]
 dc_solar_mean <- dc_solar_irradiation %>%
    filter(Month < 4) %>%
    group_by(Year) %>%
    summarise(avg_ghi = mean(GHI),
              avg_dni = mean(DNI),
              avg_dhi = mean(DHI),
              avg_clearsky = mean(Clearsky.GHI),
           avg_dew = mean(Dew.Point),
             avg_albedo = mean(Surface.Albedo),
              avg_windspeed = mean(Wind.Speed),
             avg_humidity = mean(Relative.Humidity),
             avg_temp = mean(Temperature),
             avg_pressure = mean(Pressure)
)
 dc_solar_mean <- rename(dc_solar_mean, year = Year)
 
 
 
 dc_seasonal_weather_1980s_solar <- left_join(dc_seasonal_weather_1980s,dc_solar_mean, by = "year")
 
dc_seasonal_90s <- subset(dc_seasonal_weather_1980s_solar, year >= 1999)


dc_90s_m1 <- randomForest(formula = bloom_doy ~., data = dc_seasonal_90s)

```
